effects:
  cast_mythic_skill: true
  add_mmo_stat: true
  auto_plant: true
triggers:
  advancement_done: true
  smite: true
filters:
  advancements: true
  only_on_fire: true
conditions:
  in_combat: true
settings:
  # In ticks.
  remove-combat-time: 100
