# MythicLibreforge by @PQguanfang
#
# Read the Wiki: simple.superiormc.cn

effects:
  apply_reforge: true
  cast_mythic_skill: true
  add_mmo_stat: true
  auto_plant: true
  # Require Paper
  open_anvil: true
  open_disposal: true
  open_enchanting: true
  quick_equip: true
triggers:
  # Solved libreforge's smelt trigger require player must always open UI limits.
  smelt_result: true
  # Solved libreforge's melee_attack trigger priority problems.
  highest_attack: true
filters:
  only_on_fire: true
  at_location: true
  is_crit: true
  has_enchantment: true
conditions:
  in_combat: true
arguments:
  damage_item: false
settings:
  debug: false
  # In ticks.
  remove-combat-time: 100
