name: MythicLibreforge
version: '${project.version}'
main: cn.superiormc.mythiclibreforge.MythicLibreforge
api-version: 1.17
depend:
  - eco
softdepend:
  - MythicMobs
  - MythicLib
  - MMOItems
  - MMOCore